### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by tirumalasrija** [tirumalasrija/WebMobileZWebSite#15]
testimonionals not scolling properly, remove purple color dots
![download (7)](https://user-images.githubusercontent.com/12503269/62068674-82779880-b204-11e9-9e6a-748d21886ca1.png)
 and add #d94c27 color

**Comment by ambarkumar** [comment]
Done

**Comment by tirumalasrija** [comment]
It is highlighting orange color but  i can see purple color which is not highlighting
