### ISSUE TITLE
career page

### ISSUE THREAD

**Issue by tirumalasrija** [tirumalasrija/WebMobileZWebSite#25]
remove this text box for address and Add input text 
![download (13)](https://user-images.githubusercontent.com/12503269/62073285-67118b00-b20e-11e9-8193-792e35953dcd.png)

**Comment by pvenkateshnaidu** [comment]
Resolve

**Comment by tirumalasrija** [comment]
Please remove "Senior Manager" input field, and add orange color 
Apply Buttons, List, icons on page
![web](https://user-images.githubusercontent.com/12503269/62219206-dfe22580-b37b-11e9-9e1d-9d9806b1a464.png)
