### ISSUE TITLE
Mobile Development page 

### ISSUE THREAD

**Issue by tirumalasrija** [tirumalasrija/WebMobileZWebSite#52]
![8881b678-2449-4e3c-b6cc-b7ba47e16480](https://user-images.githubusercontent.com/12503269/64451780-e8ccc200-d0b2-11e9-9c4b-defc158d768f.png)
Need to change the icons

**Comment by SrikanthReddy34** [comment]
![image](https://user-images.githubusercontent.com/32354300/65319514-70d7bf00-dbbd-11e9-81d8-96298a6cbb5d.png)
Done
